server:
  port: 8080

spring:
  application:
    name: "WebFutebol"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      dll-auto: update

  doc:
    packagesToScan: com.jogador.futebol.control

